"""Word-atlas schema constants. Not a language theorem."""

from __future__ import annotations

SCHEMA_VERSION = "juggler-word-atlas/v1"

LANG_REALIZABLE = "REALIZABLE"
LANG_EXPANDING = "EXPANDING"
LANG_PERSISTENT = "PERSISTENT"
LANG_PE_CERTIFIED = "PE_CERTIFIED"
LANG_PE_RUN = "PE_RUN"
LANG_PE_PROXY = "PE_PROXY"

LANGUAGE_IDS = (
    LANG_REALIZABLE,
    LANG_EXPANDING,
    LANG_PERSISTENT,
    LANG_PE_CERTIFIED,
    LANG_PE_RUN,
    LANG_PE_PROXY,
)

STATUS_FOUND = "FOUND"
STATUS_NOT_FOUND = "NOT_FOUND_WITHIN_BOUND"

SOURCE_CPU = "TRAJECTORY_CPU"
SOURCE_KERNEL_A = "TRAJECTORY_KERNEL_A"

PE_PROXY = "PE_PROXY"
PE_CERTIFIED = "PE_CERTIFIED"

CLAIM_LEAN = "LEAN-CERTIFIED"
CLAIM_CPU = "CPU VERIFIED"
CLAIM_GPU = "GPU VERIFIED"
CLAIM_OBSERVED = "COMPUTATIONALLY OBSERVED"
CLAIM_NOT_OBSERVED = "NOT OBSERVED WITHIN SEARCH BOUND"
CLAIM_CLOSED = "CLOSED BRANCH"
