"""Problem-independent balanced-ternary core."""

from bt.metrics import (
    RunStatistics,
    ZeroGapStatistics,
    automaton_residue,
    lsd_nonzero_index,
    negative_digit_count,
    position_class_sums,
    positive_digit_count,
    run_statistics,
    signed_digit_sum,
    v3,
    verify_invariants,
    weight,
    zero_count,
    zero_gap_statistics,
)
from bt.operators import digit_derivative, lsd_digit
from bt.polynomials import polynomial
from bt.representation import (
    BalancedTernary,
    decode,
    digits,
    encode,
    is_canonical,
    normalize,
)
from bt.sequences import (
    bt_alternating_digit_sum,
    bt_digit_sum,
    bt_is_palindrome,
    bt_length,
    bt_reverse,
    bt_reverse_tail,
    bt_reverse_zeros,
)

__all__ = [
    "BalancedTernary",
    "RunStatistics",
    "ZeroGapStatistics",
    "automaton_residue",
    "bt_alternating_digit_sum",
    "bt_digit_sum",
    "bt_is_palindrome",
    "bt_length",
    "bt_reverse",
    "bt_reverse_tail",
    "bt_reverse_zeros",
    "decode",
    "digit_derivative",
    "digits",
    "encode",
    "is_canonical",
    "lsd_digit",
    "lsd_nonzero_index",
    "negative_digit_count",
    "normalize",
    "polynomial",
    "position_class_sums",
    "positive_digit_count",
    "run_statistics",
    "signed_digit_sum",
    "v3",
    "verify_invariants",
    "weight",
    "zero_count",
    "zero_gap_statistics",
]
