"""Curated v2.2 research target board. Not live attack output and not adapters."""

from __future__ import annotations

from pathlib import Path

from research_engine.diagnosis.types import RegimeFingerprint
from research_engine.memory.types import (
    BlindPacket,
    PriorArtDossier,
    ResearchTarget,
    ScoredAxis,
    TargetBoard,
    TargetPool,
)

BOARD_PATH = Path(__file__).resolve().parent / "seed" / "target_board.json"

_AFFINE_1D = (
    "latent_piecewise_affine_control",
    "parameter_domain_certification",
    "control_word_composition",
    "control_obstruction_calculus",
)
_VECTOR = (
    "latent_vector_affine_control",
    "matrix_word_recursive_invariant",
    "infinite_reachable_trajectories",
)
_REACH = _AFFINE_1D + ("infinite_reachable_trajectories", "cycle_obstruction")


def _fp(**fields: str) -> RegimeFingerprint:
    return RegimeFingerprint(**fields)


def _axis(value: float, reason: str) -> ScoredAxis:
    return ScoredAxis(value=value, reason=reason)


def _ev_placeholder(reason: str) -> ScoredAxis:
    return ScoredAxis(value=0.0, reason=reason)


def _blind(
    spec_name: str,
    *,
    dimension: int,
    allowed_definition: str,
    state_space: str,
    observation: str,
    initial_conditions: tuple[str, ...],
    forbidden_hints: tuple[str, ...],
    explicit_controls: str = "singleton dummy control",
    computational_budget: str = "at most 16 planner steps / 32 residual states",
    skip_attacks: tuple[str, ...] = (),
    max_states: int | None = 32,
    max_steps: int | None = 16,
) -> BlindPacket:
    return BlindPacket(
        spec_name=spec_name,
        dimension=dimension,
        skip_attacks=skip_attacks,
        max_states=max_states,
        max_steps=max_steps,
        allowed_definition=allowed_definition,
        state_space=state_space,
        observation=observation,
        initial_conditions=initial_conditions,
        explicit_controls=explicit_controls,
        computational_budget=computational_budget,
        forbidden_hints=forbidden_hints,
        post_run_reconciliation="",
        lean_targets=(),
    )


def board_targets() -> tuple[ResearchTarget, ...]:
    fold_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="FINITE_CONTRACTING",
        eventual_region="FINITE_SEED_CLOSURE",
        orbit_behavior="FINITE_ORBIT",
        certificate_strength="EXACT_FINITE",
        transition_architecture="UNARY_MAP",
    )
    affine_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="EXACT_RELATION",
        piecewise_affine_structure="PARAMETERIZED",
        latent_control="PARAMETERIZED",
        parameter_domain="EXACT",
        affine_control_type="SCALAR",
    )
    vector_fp = _fp(
        state_space_type="INTEGER_VECTOR",
        control_structure="SINGLETON",
        numerical_contraction="FINITE_CONTRACTING",
        eventual_region="FINITE_SEED_CLOSURE",
        orbit_behavior="FINITE_ORBIT",
        certificate_strength="EXACT_FINITE",
        affine_control_type="VECTOR",
    )
    companion_fp = _fp(
        state_space_type="INTEGER_VECTOR",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="FINITE_RANGE",
        affine_control_type="VECTOR",
    )
    nonaffine_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="OBSERVATION",
        piecewise_affine_structure="UNCERTAIN",
    )

    decrement = ResearchTarget(
        name="slc_decrement",
        canonical_definition="while x >= 1 do x := x - 1",
        state_space="Z",
        transition_type="affine_guarded",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="singleton affine",
        known_regime_if_any="terminating ranking function",
        open_question="None for this instance.",
        known_results=("terminates from every integer",),
        known_obstructions=(),
        computational_status="settled",
        prior_art_saturation="fully settled elementary ranking example",
        engine_fit=_axis(0.9, "1-D affine guard; control-word stack already consumed this instance"),
        structural_distance=_axis(0.05, "already in the historical corpus as a known loop"),
        novelty_potential=_axis(0.15, "prior art classified; no open question"),
        failure_learning_value=_axis(0.2, "failure would only repeat a saturated competence check"),
        experimental_cost=_axis(0.5, "existing adapter; tiny window"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.CALIBRATION,
        priority="low after competence",
        recommended_protocol="blind replay of the existing spec; confirm ranking, then CLOSE",
        claimed_capabilities=("finite_closure", "cycle_obstruction"),
        prior_art_classified=True,
        prospective_fingerprint=fold_fp,
        already_run=True,
        prior_art=PriorArtDossier(
            target="slc_decrement",
            definition="while x >= 1 do x := x - 1",
            known_theorems=("Affine SLC termination over Z is decidable.",),
            open_question="None.",
            open_question_confidence="settled",
            literature_ids=("carelli-2026-loop-termination", "hosseini-ouaknine-worrell-2019-termination-linear-loops"),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "slc_decrement",
            dimension=1,
            allowed_definition="while x >= 1 do x := x - 1",
            state_space="Z",
            observation="the integer state",
            initial_conditions=("8",),
            forbidden_hints=("named conjectures", "open-problem status", "literature reductions"),
        ),
    )

    euclidean = ResearchTarget(
        name="euclidean_remainder",
        canonical_definition="(a, b) maps to (b, a mod b) when b != 0, else halt",
        state_space="Z^2",
        transition_type="vector_affine",
        dimension=2,
        determinism="DETERMINISTIC",
        known_control_type="vector remainder",
        known_regime_if_any="finite terminating gcd",
        open_question="None for termination of the Euclidean algorithm.",
        known_results=("gcd is computed; orbits finite",),
        known_obstructions=("scalar affine census inapplicable",),
        computational_status="settled",
        prior_art_saturation="classical; engine already recovered the matrix language",
        engine_fit=_axis(0.85, "vector_affine already recovered remainder dynamics"),
        structural_distance=_axis(0.1, "historical euclidean_quotient fingerprint"),
        novelty_potential=_axis(0.15, "prior art classified"),
        failure_learning_value=_axis(0.25, "low; competence already shown in dimension 2"),
        experimental_cost=_axis(0.8, "existing adapter"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.CALIBRATION,
        priority="low after competence",
        recommended_protocol="replay vector remainder; confirm matrix recovery; CLOSE",
        claimed_capabilities=("latent_vector_affine_control", "finite_closure"),
        prior_art_classified=True,
        prospective_fingerprint=vector_fp,
        already_run=True,
        prior_art=PriorArtDossier(
            target="euclidean_remainder",
            definition="(a,b) |-> (b, a mod b)",
            known_theorems=("Euclidean algorithm terminates.",),
            literature_ids=("knuth-taocp-vol2", "vallee-2006-euclidean-algorithm"),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "euclidean_quotient",
            dimension=2,
            allowed_definition="(a, b) maps to (b, a mod b) when b != 0 else halt",
            state_space="Z^2",
            observation="both coordinates",
            initial_conditions=("(13, 8)",),
            forbidden_hints=("named conjectures", "known cycle theorem"),
        ),
    )

    aliquot12 = ResearchTarget(
        name="aliquot_seed_12",
        canonical_definition="n maps to the sum of proper divisors of n, seed 12",
        state_space="positive integers",
        transition_type="divisor_sum",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="none affine",
        known_regime_if_any="known terminating orbit",
        open_question="None for seed 12.",
        known_results=("12 reaches 0",),
        known_obstructions=("no piecewise-affine cover",),
        computational_status="settled for this seed",
        prior_art_saturation="classical terminating sequence",
        engine_fit=_axis(0.35, "non-affine; used only as a finite-orbit calibration"),
        structural_distance=_axis(0.7, "outside residue-affine language"),
        novelty_potential=_axis(0.15, "known terminating seed"),
        failure_learning_value=_axis(0.4, "confirms the non-affine cluster on a settled orbit"),
        experimental_cost=_axis(0.6, "existing divisor-sum spec, tiny seed"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.CALIBRATION,
        priority="low after competence",
        recommended_protocol="finite closure of seed 12; refuse an affine cover; CLOSE",
        claimed_capabilities=("finite_closure",),
        prior_art_classified=True,
        prospective_fingerprint=fold_fp,
        already_run=True,
        prior_art=PriorArtDossier(
            target="aliquot_seed_12",
            definition="n |-> sigma(n)-n from 12",
            known_theorems=("seed 12 terminates",),
            literature_ids=("oeis-A008892",),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "aliquot_seed_12",
            dimension=1,
            allowed_definition="n maps to the sum of proper divisors of n",
            state_space="positive integers",
            observation="the integer n",
            initial_conditions=("12",),
            forbidden_hints=("named conjectures", "open-problem status", "cycle names"),
        ),
    )

    amicable = ResearchTarget(
        name="aliquot_amicable_220",
        canonical_definition="n maps to the sum of proper divisors of n, seed 220",
        state_space="positive integers",
        transition_type="divisor_sum",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="none affine",
        known_regime_if_any="known 2-cycle",
        open_question="None for the 220-284 cycle.",
        known_results=("220 and 284 form a 2-cycle",),
        known_obstructions=("no piecewise-affine cover",),
        computational_status="settled",
        prior_art_saturation="classical amicable pair",
        engine_fit=_axis(0.3, "same non-affine map as seed 12; cycle rather than halt"),
        structural_distance=_axis(0.7, "outside residue-affine language"),
        novelty_potential=_axis(0.15, "known cycle"),
        failure_learning_value=_axis(0.35, "low; another settled divisor-sum orbit"),
        experimental_cost=_axis(0.6, "existing spec"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.CALIBRATION,
        priority="low after competence",
        recommended_protocol="optional; not in the first calibration triple",
        claimed_capabilities=("finite_closure",),
        prior_art_classified=True,
        prospective_fingerprint=fold_fp,
        already_run=True,
        blind_packet=_blind(
            "aliquot_amicable_220",
            dimension=1,
            allowed_definition="n maps to the sum of proper divisors of n",
            state_space="positive integers",
            observation="the integer n",
            initial_conditions=("220",),
            forbidden_hints=("cycle names", "named conjectures"),
        ),
    )

    skolem2 = ResearchTarget(
        name="skolem_order2_known_zero",
        canonical_definition="companion window in Z^2 for a declared order-2 recurrence with a known first-coordinate zero",
        state_space="Z^2 companion windows",
        transition_type="linear_companion",
        dimension=2,
        determinism="DETERMINISTIC",
        known_control_type="vector companion",
        known_regime_if_any="known zero at a small index",
        open_question="None for the calibration window.",
        known_results=("first coordinate vanishes at a certified small index",),
        known_obstructions=(),
        computational_status="settled calibration",
        prior_art_saturation="order <= 4 decidable; this instance is a known zero",
        engine_fit=_axis(0.8, "vector companion already recovered in dimension 2"),
        structural_distance=_axis(0.15, "matches historical easy companion calibrations"),
        novelty_potential=_axis(0.15, "known zero"),
        failure_learning_value=_axis(0.2, "low; competence check only"),
        experimental_cost=_axis(0.7, "existing companion spec"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.CALIBRATION,
        priority="low after competence",
        recommended_protocol="optional calibration; not in the first triple",
        claimed_capabilities=("latent_vector_affine_control", "finite_closure"),
        prior_art_classified=True,
        prospective_fingerprint=vector_fp,
        already_run=True,
        blind_packet=_blind(
            "companion_shift_order2",
            dimension=2,
            allowed_definition="window (u, v) maps to (v, a v + b u) for declared integers a, b",
            state_space="Z^2",
            observation="first coordinate",
            initial_conditions=("declared order-2 window",),
            forbidden_hints=("named conjectures", "known congruence of zeros", "open-problem status"),
        ),
    )

    syracuse = ResearchTarget(
        name="mx_plus_r_3x1",
        canonical_definition="y = (3x+1)/2^{v_2(3x+1)} on odd positive x",
        state_space="odd positive integers",
        transition_type="valuation_affine",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="parameterized 2-adic affine",
        known_regime_if_any="residue-controlled affine family reconstructed",
        open_question="Global convergence is the classical question and is not this campaign's target.",
        known_results=("family 2^k y = 3x+1", "exact domain of k"),
        known_obstructions=("window agreement is not a Z-theorem",),
        computational_status="language reconstructed; global map open and out of scope",
        prior_art_saturation="saturated for rediscovery",
        engine_fit=_axis(0.9, "this is the engine's demonstrated sweet spot"),
        structural_distance=_axis(0.05, "historical Syracuse fingerprint"),
        novelty_potential=_axis(0.1, "KNOWN rediscovery"),
        failure_learning_value=_axis(0.2, "would only repeat prior-art saturation"),
        experimental_cost=_axis(1.0, "existing adapter"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.CALIBRATION,
        priority="low after competence",
        recommended_protocol="do not re-run as a first campaign target",
        claimed_capabilities=_AFFINE_1D,
        prior_art_classified=True,
        prospective_fingerprint=affine_fp,
        already_run=True,
        blind_packet=_blind(
            "syracuse",
            dimension=1,
            allowed_definition="odd x maps to (3x+1) divided by the maximal power of 2 that divides it",
            state_space="odd positive integers",
            observation="the integer",
            initial_conditions=("7",),
            forbidden_hints=("named conjectures", "known residue partition", "open-problem status"),
        ),
    )

    order6 = ResearchTarget(
        name="companion_shift_order6_zero_class",
        canonical_definition=(
            "companion-window iteration on Z^6 for a declared order-6 integer recurrence; "
            "observation is the first coordinate"
        ),
        state_space="Z^6 companion windows",
        transition_type="linear_companion",
        dimension=6,
        determinism="DETERMINISTIC",
        known_control_type="vector companion",
        known_regime_if_any="matrix recovered; finite search exhausted",
        open_question=(
            "Can matrix-word / lattice-gcd structure recover a congruence constraint on "
            "vanishing indices without interpolants?"
        ),
        known_results=("companion matrix in dimension 2 calibrations", "no zero on {0,...,64}"),
        known_obstructions=("3-point census cannot fit dimension >= 3", "25^6 cube skipped"),
        computational_status="finite prefix known; infinite vanishing unresolved",
        prior_art_saturation="high on the sequence; the modular-obstruction question is the remaining engine test",
        engine_fit=_axis(0.75, "companion representation fits; census cannot be run at d=6"),
        structural_distance=_axis(0.2, "same vector-unbounded fingerprint as the historical run"),
        novelty_potential=_axis(0.45, "question is an intermediate constraint, not a decision procedure"),
        failure_learning_value=_axis(
            0.9,
            "failure would recur the global-reachability cluster and the computational census barrier",
        ),
        experimental_cost=_axis(2.0, "high-dimensional census skip; lattice probes only"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.FRONTIER,
        priority="frontier; already-run instance with a sharper intermediate question",
        recommended_protocol="do not claim non-existence; ask only for a class constraint on zeros",
        claimed_capabilities=_VECTOR,
        prior_art_classified=True,
        prospective_fingerprint=companion_fp,
        already_run=True,
        prior_art=PriorArtDossier(
            target="companion_shift_order6_zero_class",
            definition="first-coordinate vanishing of a declared order-6 companion window",
            known_equivalent_formulations=(
                "linear recurrence vanishing",
                "orbit of a companion matrix hitting a coordinate hyperplane",
            ),
            known_theorems=(
                "zeros of a non-degenerate LRS are a finite set union arithmetic progressions",
                "unconditional decidability through order 4",
            ),
            known_conjectures=("conditional general decidability under number-theoretic hypotheses",),
            known_computational_results=("no zero on a huge finite prefix for the survey instance",),
            known_methods=("p-adic interpolants", "MSTV class", "modular invariants"),
            known_barriers=("no modular exclusion of all zeros", "outside MSTV"),
            open_question="Does a lattice/gcd word invariant constrain vanishing indices?",
            open_question_confidence="literature-open for vanishing; engine-open for the congruence",
            current_literature_activity="active (2022-2026 survey and conditional results)",
            literature_ids=(
                "bacik-et-al-2026-skolem-positivity-survey",
                "kenison-et-al-2025-order-4-skolem",
                "lipton-et-al-2022-skolem-conjecture",
            ),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "companion_shift_order6",
            dimension=6,
            allowed_definition="window x maps to M x for a declared 6x6 companion matrix of an integer recurrence",
            state_space="Z^6",
            observation="first coordinate",
            initial_conditions=("declared order-6 window",),
            forbidden_hints=(
                "named conjectures",
                "known congruence of zeros",
                "interpolant methods",
                "open-problem status",
                "literature reductions",
            ),
            skip_attacks=(),
            computational_budget="max index 64; skip 25^d cubes above 50000 cells",
        ),
    )

    floor54 = ResearchTarget(
        name="weak_collatz_floor_5x4_rplus",
        canonical_definition=(
            "one-variable integer loop whose graph is the integer points of the strip "
            "defined by 5x - 4 <= 4 x' <= 5x - 1 with x >= 2 (the expanding branch of T(x)=floor(5x/4))"
        ),
        state_space="Z, x >= 2",
        transition_type="one_variable_linear_constraint",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="residue-controlled affine (to be discovered, not supplied)",
        known_regime_if_any="expected parameterized affine on residues mod 4",
        open_question="Does every orbit lose its successor (hit a multiple of 4)?",
        known_results=("weak maps with modulus 2 are decided; modulus > 2 remain open",),
        known_obstructions=("Reachability Conjecture for m=5, d=4",),
        computational_status="small seeds empirically halt; no theorem",
        prior_art_saturation="construction known; this (m,d) instance was not run",
        engine_fit=_axis(0.85, "same SLC/residue-affine language as the reconstructed 4/3 loop, different moduli"),
        structural_distance=_axis(
            0.35,
            "same mixed-magnitude parameterized 1-D class as the 4/3 loop, different strip",
        ),
        novelty_potential=_axis(0.7, "open instance distinct from the already-run 4/3 loop"),
        failure_learning_value=_axis(
            0.85,
            "failure would recur global reachability on a new open SLC, not a rediscovery of the 4/3 loop",
        ),
        experimental_cost=_axis(1.2, "new adapter later; frozen attacks only"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.FRONTIER,
        priority="high; recommended first distinct SLC",
        recommended_protocol="blind inequality spec; reconstruct branches; stop before a universal halt claim",
        claimed_capabilities=_REACH,
        prior_art_classified=True,
        prospective_fingerprint=affine_fp,
        prior_art=PriorArtDossier(
            target="weak_collatz_floor_5x4_rplus",
            definition="integer SLC for the expanding locus of T(x)=floor(5x/4)",
            known_equivalent_formulations=(
                "weak mapping T(x)=(5x-i)/4 on 5x ≡ i (mod 4)",
                "one-variable linear-constraint loop of the R+ construction",
            ),
            known_theorems=(
                "a cyclic trace implies a cyclic trace of length at most two",
                "Reachability Conjecture holds for modulus 2",
            ),
            known_conjectures=("Reachability Conjecture for this T",),
            known_methods=("Minkowski-Weyl decomposition of the transition polyhedron",),
            known_barriers=("modulus d>2 remain open",),
            open_question="Termination of this SLC / reachability of multiples of 4 under T",
            open_question_confidence="open; not the already-run 4/3 instance",
            current_literature_activity="active (2026 loop-termination paper)",
            literature_ids=(
                "carelli-2026-loop-termination",
                "matthews-watts-1984-generalization-hasse",
                "ben-amram-genaim-ouaknine-worrell-2025-termination-survey",
            ),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "floor_5x4_strip",
            dimension=1,
            allowed_definition="integer x >= 2 maps to the unique integer x' with 5x-4 <= 4 x' <= 5x-1 when it exists",
            state_space="Z",
            observation="the integer x",
            initial_conditions=("5",),
            forbidden_hints=(
                "named conjectures",
                "known residue partition",
                "open-problem status",
                "literature reductions",
                "cycle theorems",
            ),
        ),
    )

    matthews = ResearchTarget(
        name="matthews_prize_mod3_avoider",
        canonical_definition=(
            "T(x)=2x if x ≡ 0 (mod 3); T(x)=(7x+2)/3 if x ≡ 1 (mod 3); "
            "T(x)=(x-2)/3 if x ≡ 2 (mod 3)"
        ),
        state_space="Z",
        transition_type="residue_affine",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="three residue-affine branches",
        known_regime_if_any="0 (mod 3) is invariant and expanding",
        open_question=(
            "If an orbit stays in {1,2} (mod 3) for all time, does it enter the 1-cycle at -1 "
            "or the 2-cycle {-2,-4}?"
        ),
        known_results=("once 0 mod 3 is hit the orbit stays there and diverges", "cycles at -1 and {-2,-4}"),
        known_obstructions=("no proof that ±1-mod-3 orbits cannot avoid those cycles",),
        computational_status="experimental evidence for the cycle claim; no theorem",
        prior_art_saturation="map known; the avoider-to-cycle claim is the unresolved intermediate",
        engine_fit=_axis(0.85, "residue-controlled affine language already reconstructed on other maps"),
        structural_distance=_axis(0.4, "three-branch mod-3 map, not the 4/3 strip and not the 5/3 partial map"),
        novelty_potential=_axis(0.75, "specific cycle-avoidance question, not general convergence"),
        failure_learning_value=_axis(
            0.8,
            "failure would recur global reachability on a distinct residue-affine open question",
        ),
        experimental_cost=_axis(1.3, "new adapter later; three-branch census"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.FRONTIER,
        priority="high; distinct residue-affine reachability instance",
        recommended_protocol="blind residue map; reconstruct branches; attack the avoider class, not totality",
        claimed_capabilities=_REACH,
        prior_art_classified=True,
        prospective_fingerprint=affine_fp,
        prior_art=PriorArtDossier(
            target="matthews_prize_mod3_avoider",
            definition="the three-branch mod-3 integer map displayed in the canonical definition",
            known_equivalent_formulations=("generalized Syracuse map of relatively prime type, d=3",),
            known_theorems=("0 (mod 3) is invariant",),
            known_conjectures=("avoiding orbits enter the known cycles at -1 or {-2,-4}",),
            known_computational_results=("experimental support for the cycle claim",),
            known_methods=("Markov chain models on residue classes",),
            known_barriers=("same intractability class as the classical 3x+1 totality question",),
            open_question="Do ±1-mod-3 orbits that never hit 0 mod 3 enter the known cycles?",
            open_question_confidence="open; not a totality claim",
            current_literature_activity="classical; still cited as a simple open avoider",
            literature_ids=("matthews-watts-1984-generalization-hasse",),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "mod3_three_branch",
            dimension=1,
            allowed_definition=(
                "T(x)=2x when 3|x; T(x)=(7x+2)/3 when x ≡ 1 (mod 3); "
                "T(x)=(x-2)/3 when x ≡ 2 (mod 3)"
            ),
            state_space="Z",
            observation="the integer x",
            initial_conditions=("1", "5"),
            forbidden_hints=(
                "named conjectures",
                "known cycle theorem",
                "open-problem status",
                "literature reductions",
                "prize claims",
            ),
        ),
    )

    switching = ResearchTarget(
        name="switching_affine_z2_origin",
        canonical_definition=(
            "deterministic two-path integer loop on Z^2: if y >= 1 then (x,y):=(x+y, y-1) "
            "else if x >= 1 then (x,y):=(x-1, x+y) else halt"
        ),
        state_space="Z^2",
        transition_type="switching_affine",
        dimension=2,
        determinism="DETERMINISTIC",
        known_control_type="two-piece vector affine",
        known_regime_if_any="multi-path 2-variable integer loop; termination not supplied",
        open_question="Is (0,0) reachable from (3,2)? Does the loop terminate from every N^2 seed?",
        known_results=("single-update affine loops over Z are decidable",),
        known_obstructions=("multi-path integer loops remain open in general",),
        computational_status="finite seeds tractable; universal termination unresolved",
        prior_art_saturation="class open; this explicit two-path instance is a locked representative",
        engine_fit=_axis(0.8, "vector_affine plus matrix-word on a real 2-D switching system"),
        structural_distance=_axis(0.55, "2-D switching, not a companion window and not Euclidean gcd"),
        novelty_potential=_axis(0.7, "unresolved 2-variable termination/reachability, exact semantics"),
        failure_learning_value=_axis(
            0.8,
            "failure tests whether vector/matrix machinery yields leverage beyond companion recovery",
        ),
        experimental_cost=_axis(1.5, "2-D census cheaper than order-6; new adapter later"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.FRONTIER,
        priority="high; 2-D matrix/switching test",
        recommended_protocol="blind two-piece spec; recover A_u,x+b_u; origin reachability only",
        claimed_capabilities=_VECTOR + ("cycle_obstruction",),
        prior_art_classified=True,
        prospective_fingerprint=_fp(
            state_space_type="INTEGER_VECTOR",
            control_structure="SINGLETON",
            numerical_contraction="MIXED_MAGNITUDE",
            eventual_region="UNBOUNDED_SAMPLE",
            orbit_behavior="MIXED",
            certificate_strength="OBSERVATION",
            affine_control_type="VECTOR",
        ),
        already_run=True,
        prior_art=PriorArtDossier(
            target="switching_affine_z2_origin",
            definition="priority two-path affine updates on Z^2 as in the canonical definition",
            known_equivalent_formulations=(
                "multi-path linear-constraint loop in two integer variables",
                "2-mode discrete linear hybrid automaton on Z^2",
            ),
            known_theorems=("termination of purely affine (single-update) integer loops is decidable",),
            known_conjectures=("general multi-path integer-loop termination remains open",),
            known_methods=("ranking functions", "vector-affine census", "matrix-word invariants"),
            known_barriers=("piecewise updates leave the decidable affine-SLC fragment",),
            open_question="origin reachability / termination of this two-path loop",
            open_question_confidence="origin on N^2 classified; universal Z^2 termination unresolved",
            current_literature_activity="active surveys of linear-constraint termination",
            literature_ids=(
                "ben-amram-genaim-ouaknine-worrell-2025-termination-survey",
                "hosseini-ouaknine-worrell-2019-termination-linear-loops",
            ),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "two_path_z2",
            dimension=2,
            allowed_definition=(
                "if y >= 1 then (x,y):=(x+y, y-1); else if x >= 1 then (x,y):=(x-1, x+y); else halt"
            ),
            state_space="Z^2",
            observation="both coordinates",
            initial_conditions=("(3, 2)",),
            forbidden_hints=(
                "named conjectures",
                "open-problem status",
                "literature reductions",
                "known ranking function",
            ),
        ),
    )

    seven = ResearchTarget(
        name="mx_plus_r_7x1_class_obstruction",
        canonical_definition="y = (7x+1)/2^{v_2(7x+1)} on odd positive x; question is a class obstruction to hitting 1",
        state_space="odd positive integers",
        transition_type="valuation_affine",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="parameterized 2-adic affine",
        known_regime_if_any="same (mx+r) family already reconstructed for several odd (m,r)",
        open_question="Does a control-word class obstruction exclude an infinite family from reaching 1?",
        known_results=("family 2^k y = 7x+1 is the expected reconstruction",),
        known_obstructions=("rediscovery of the family is not a new theorem",),
        computational_status="language likely already exercised; class obstruction to 1 is the question",
        prior_art_saturation="high for the family; medium for a 7-specific class constraint",
        engine_fit=_axis(0.8, "identical language to the reconstructed 3x+1 family"),
        structural_distance=_axis(0.1, "core fingerprint matches the historical mx+r family"),
        novelty_potential=_axis(0.4, "prior art classified; value is a class obstruction, not rediscovery"),
        failure_learning_value=_axis(
            0.45,
            "likely prior-art saturation; keep only if EV does not collapse",
        ),
        experimental_cost=_axis(1.0, "existing mx+r spec"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.FRONTIER,
        priority="conditional; include only if EV is not saturated-family collapse",
        recommended_protocol="if the family is rediscovered, spend the budget on class obstruction to 1, then stop",
        claimed_capabilities=_REACH,
        prior_art_classified=True,
        prospective_fingerprint=affine_fp,
        prior_art=PriorArtDossier(
            target="mx_plus_r_7x1_class_obstruction",
            definition="accelerated 7x+1 map",
            known_theorems=("the accelerated odd map is well-defined",),
            known_conjectures=("most trajectories believed divergent for 5x+1 / 7x+1 relatives",),
            literature_ids=("crandall-1978-3x+1", "chamberland-2003-3x+1-survey"),
            last_checked="2026-08-25",
            open_question="class obstruction to reaching 1",
            open_question_confidence="open as a map theorem; family reconstruction is KNOWN",
        ),
        blind_packet=_blind(
            "mx_plus_r_7_1",
            dimension=1,
            allowed_definition="odd x maps to (7x+1) divided by the maximal power of 2 that divides it",
            state_space="odd positive integers",
            observation="the integer",
            initial_conditions=("3",),
            forbidden_hints=("named conjectures", "open-problem status", "known residue partition"),
        ),
    )

    order5 = ResearchTarget(
        name="skolem_order5_unconditional",
        canonical_definition=(
            "companion-window iteration on Z^5 for a declared order-5 integer recurrence "
            "whose first-coordinate vanishing is not covered by the unconditional order-4 decision procedure"
        ),
        state_space="Z^5 companion windows",
        transition_type="linear_companion",
        dimension=5,
        determinism="DETERMINISTIC",
        known_control_type="vector companion",
        known_regime_if_any="same companion language as order 6; different dimension",
        open_question="Does the first coordinate vanish? Can the engine do more than exhaust a finite prefix?",
        known_results=("order <= 4 decided", "order 5 only conditionally decided"),
        known_obstructions=("vector census cube in dimension 5 is 25^5",),
        computational_status="unconditionally open; finite prefixes tractable",
        prior_art_saturation="high as a decision problem; this is a different instance from the order-6 flagship",
        engine_fit=_axis(0.7, "companion fits; census exhaustion expected at d=5"),
        structural_distance=_axis(0.25, "same unbounded vector class, new dimension and recurrence"),
        novelty_potential=_axis(0.55, "different instance; still a vanishing question"),
        failure_learning_value=_axis(
            0.75,
            "tests whether dim-5 census exhaustion is the same computational cluster as dim-6",
        ),
        experimental_cost=_axis(2.2, "5-D census likely skipped"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.FRONTIER,
        priority="frontier; second companion instance",
        recommended_protocol="blind companion spec; finite zero search; no interpolant language",
        claimed_capabilities=_VECTOR,
        prior_art_classified=True,
        prospective_fingerprint=companion_fp,
        prior_art=PriorArtDossier(
            target="skolem_order5_unconditional",
            definition="first-coordinate vanishing of a declared order-5 companion window",
            known_theorems=("unconditional decidability through order 4",),
            known_conjectures=("conditional order-5 procedures under number-theoretic hypotheses",),
            known_barriers=("unconditional order-5 remains open",),
            open_question="first-coordinate vanishing of this order-5 window",
            open_question_confidence="unconditionally open",
            current_literature_activity="active",
            literature_ids=(
                "bacik-et-al-2026-skolem-positivity-survey",
                "lipton-et-al-2022-skolem-conjecture",
                "kenison-et-al-2025-order-4-skolem",
            ),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "companion_shift_order5",
            dimension=5,
            allowed_definition="window x maps to M x for a declared 5x5 companion matrix of an integer recurrence",
            state_space="Z^5",
            observation="first coordinate",
            initial_conditions=("declared order-5 window",),
            forbidden_hints=(
                "named conjectures",
                "interpolant methods",
                "open-problem status",
                "known congruence of zeros",
            ),
        ),
    )

    aliquot276 = ResearchTarget(
        name="aliquot_276",
        canonical_definition="n maps to the sum of proper divisors of n, seed 276",
        state_space="positive integers",
        transition_type="divisor_sum",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="none affine",
        known_regime_if_any="open long-term fate; prefix matches the published table",
        open_question="Does seed 276 reach 0 or a cycle?",
        known_results=("prefix agreement with the published sequence table", "descent refuted at 12"),
        known_obstructions=("no piecewise-affine cover",),
        computational_status="open; factorization-capped",
        prior_art_saturation="high; already run as the wildcard baseline",
        engine_fit=_axis(0.15, "outside affine/valuation control"),
        structural_distance=_axis(0.85, "factorization dynamics"),
        novelty_potential=_axis(0.2, "already run; KNOWN rediscovery of the prefix"),
        failure_learning_value=_axis(0.7, "baseline of the non-affine cluster; do not re-run first"),
        experimental_cost=_axis(1.5, "factorization budget"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.WILDCARD,
        priority="historical baseline; not first wildcard",
        recommended_protocol="already PARKED; keep as loot, do not re-run first",
        claimed_capabilities=("finite_closure", "growth"),
        prior_art_classified=True,
        prospective_fingerprint=nonaffine_fp,
        already_run=True,
        prior_art=PriorArtDossier(
            target="aliquot_276",
            definition="n |-> sigma(n)-n from 276",
            known_conjectures=("every sequence terminates or becomes periodic",),
            literature_ids=("oeis-A008892", "guy-selfridge-1975-aliquot-drivers"),
            last_checked="2026-08-25",
            open_question="fate of 276",
            open_question_confidence="open",
        ),
        blind_packet=_blind(
            "aliquot_276",
            dimension=1,
            allowed_definition="n maps to the sum of proper divisors of n",
            state_space="positive integers",
            observation="the integer n",
            initial_conditions=("276",),
            forbidden_hints=("named conjectures", "open-problem status", "published term counts"),
            max_states=32,
        ),
    )

    home = ResearchTarget(
        name="home_prime_49",
        canonical_definition="n maps to the integer obtained by concatenating its prime factors in ascending order, seed 49",
        state_space="positive integers >= 2",
        transition_type="factorization_concatenation",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="none affine",
        known_regime_if_any="factorization-dependent; some seeds reach a prime",
        open_question="Does seed 49 reach a prime?",
        known_results=("some seeds reach a prime in few steps",),
        known_obstructions=("no affine/valuation control",),
        computational_status="open for several seeds including 49",
        prior_art_saturation="computational folklore; not an affine literature",
        engine_fit=_axis(0.15, "factorization concatenation is outside the frozen language"),
        structural_distance=_axis(0.9, "non-affine arithmetic; transfer of the divisor-sum cluster"),
        novelty_potential=_axis(0.4, "different map, same language-boundary test"),
        failure_learning_value=_axis(
            0.75,
            "high-value if it recurs the non-affine cluster; low-value if it is an obvious incompatibility with no reusable lesson",
        ),
        experimental_cost=_axis(1.4, "factorization-capped adapter later"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.WILDCARD,
        priority="wildcard transfer test",
        recommended_protocol="exact factorization-capped transition; refuse an affine cover; do not build a dedicated attack",
        claimed_capabilities=("growth",),
        prior_art_classified=True,
        prospective_fingerprint=nonaffine_fp,
        prior_art=PriorArtDossier(
            target="home_prime_49",
            definition="concatenate prime factors of n, iterate from 49",
            known_computational_results=("some seeds reach primes; 49 is a long-standing unfinished seed",),
            open_question="does 49 reach a prime?",
            open_question_confidence="computationally open",
            literature_ids=("oeis-A037274",),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "home_prime_49",
            dimension=1,
            allowed_definition="n maps to the concatenation of its prime factors written in ascending order",
            state_space="integers >= 2",
            observation="the integer n",
            initial_conditions=("49",),
            forbidden_hints=("named conjectures", "open-problem status", "published unfinished seeds"),
        ),
    )

    juggler = ResearchTarget(
        name="juggler_sequence",
        canonical_definition="n even maps to floor(sqrt(n)); n odd maps to floor(n^{3/2})",
        state_space="positive integers",
        transition_type="nonlinear_integer",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="none affine",
        known_regime_if_any="nonlinear floor powers",
        open_question="Does every positive seed reach 1?",
        known_results=("small seeds reach 1; some seeds have huge excursions",),
        known_obstructions=("not residue-affine",),
        computational_status="open; verified on large finite ranges",
        prior_art_saturation="computational; no affine reconstruction expected",
        engine_fit=_axis(0.2, "nonlinear floors are outside affine control"),
        structural_distance=_axis(0.85, "new nonlinear integer class"),
        novelty_potential=_axis(0.5, "real open question with exact I/O"),
        failure_learning_value=_axis(
            0.55,
            "medium: a new non-affine class, reusable only if the fingerprint is distinct from divisor-sum",
        ),
        experimental_cost=_axis(1.1, "cheap exact I/O; huge intermediates possible"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.WILDCARD,
        priority="wildcard nonlinear test",
        recommended_protocol="exact floor map; diagnose regime; do not add a radical attack",
        claimed_capabilities=("growth", "finite_closure"),
        prior_art_classified=True,
        prospective_fingerprint=nonaffine_fp,
        prior_art=PriorArtDossier(
            target="juggler_sequence",
            definition="even n -> floor(sqrt(n)); odd n -> floor(n^{3/2})",
            known_computational_results=("all seeds below large bounds reach 1",),
            open_question="universal reachability of 1",
            open_question_confidence="open",
            literature_ids=("oeis-A007320",),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "juggler",
            dimension=1,
            allowed_definition="even n maps to floor(sqrt(n)); odd n maps to floor(n**(3/2))",
            state_space="positive integers",
            observation="the integer n",
            initial_conditions=("13",),
            forbidden_hints=("named conjectures", "open-problem status"),
        ),
    )

    reverse_add = ResearchTarget(
        name="reverse_and_add_base3",
        canonical_definition="n maps to n plus the integer whose balanced-ternary digits are the reverse of those of n",
        state_space="integers",
        transition_type="digit_reverse_add",
        dimension=1,
        determinism="DETERMINISTIC",
        known_control_type="none affine",
        known_regime_if_any="digit reverse; palindrome attractors possible",
        open_question="Does every seed reach a palindrome in this digit system?",
        known_results=("base-10 analogue is classically open for some seeds",),
        known_obstructions=("not residue-affine",),
        computational_status="open analogue; finite palindrome checks tractable",
        prior_art_saturation="base-10 lore must not be injected; base-3 instance is a laboratory analogue",
        engine_fit=_axis(0.25, "digit reverse is not affine control"),
        structural_distance=_axis(0.8, "digit-reverse vs digit-fold vs affine"),
        novelty_potential=_axis(0.45, "exact map; palindrome reachability is the question"),
        failure_learning_value=_axis(
            0.5,
            "medium: distinguishes reverse-add from digit-fold saturation and from factorization",
        ),
        experimental_cost=_axis(1.0, "exact reverse already exists in the core; adapter later"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.WILDCARD,
        priority="wildcard digit-reverse test",
        recommended_protocol="exact reverse-plus-add; no palindrome conjecture language on the adapter",
        claimed_capabilities=("finite_closure", "growth"),
        prior_art_classified=True,
        prospective_fingerprint=nonaffine_fp,
        prior_art=PriorArtDossier(
            target="reverse_and_add_base3",
            definition="n |-> n + reverse_digits(n) in balanced ternary",
            known_equivalent_formulations=("base-10 reverse-and-add / palindrome iteration",),
            known_conjectures=("some base-10 seeds are believed never to palindrome",),
            open_question="palindrome reachability in this digit system",
            open_question_confidence="open analogue; do not import base-10 status as a theorem",
            literature_ids=("oeis-A134028",),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "reverse_add_bt",
            dimension=1,
            allowed_definition="n maps to n plus the integer whose balanced-ternary digits reverse those of n",
            state_space="integers",
            observation="the integer n",
            initial_conditions=("196",),
            forbidden_hints=(
                "named conjectures",
                "open-problem status",
                "palindrome conjectures",
                "base-10 folklore",
            ),
        ),
    )

    tag = ResearchTarget(
        name="cyclic_tag_bit",
        canonical_definition=(
            "cyclic tag on the alphabet {0,1} with production 0 |-> 0 and 1 |-> 11; "
            "halt when the word is empty"
        ),
        state_space="finite binary words",
        transition_type="combinatorial_rewriting",
        dimension=0,
        determinism="DETERMINISTIC",
        known_control_type="none affine",
        known_regime_if_any="rewriting / tag system",
        open_question="Does the declared seed word halt?",
        known_results=("some productions halt; some tag families encode hard reachability",),
        known_obstructions=("state is a word, not an integer vector",),
        computational_status="instance-wise; halt of this seed is the question",
        prior_art_saturation="rewriting literature; poor engine fit by design",
        engine_fit=_axis(0.05, "word rewriting is outside the integer ProblemSpec sweet spot"),
        structural_distance=_axis(1.0, "deliberately far"),
        novelty_potential=_axis(0.3, "exact halt question; likely representation mismatch"),
        failure_learning_value=_axis(
            0.25,
            "low unless the mismatch is reusable; obvious incompatibility is low-value",
        ),
        experimental_cost=_axis(1.2, "would need a word-state encoding later; not this phase"),
        expected_research_value=_ev_placeholder("computed by score_candidate"),
        pool=TargetPool.WILDCARD,
        priority="deprioritize if failure-learning stays low",
        recommended_protocol="measure representation mismatch; do not build a tag-system attack",
        claimed_capabilities=("growth",),
        prior_art_classified=True,
        prospective_fingerprint=nonaffine_fp,
        prior_art=PriorArtDossier(
            target="cyclic_tag_bit",
            definition="cyclic tag 0|->0, 1|->11, halt on empty word",
            known_theorems=("tag systems can encode hard reachability",),
            open_question="halt of the declared seed",
            open_question_confidence="instance-wise",
            literature_ids=("baader-nipkow-1998-term-rewriting",),
            last_checked="2026-08-25",
        ),
        blind_packet=_blind(
            "cyclic_tag_bit",
            dimension=1,
            allowed_definition="rewrite a binary word by the productions 0 |-> 0 and 1 |-> 11, cyclic, halt on empty",
            state_space="finite binary words encoded as integers if needed",
            observation="word length",
            initial_conditions=("101",),
            forbidden_hints=("named conjectures", "open-problem status", "universality claims"),
        ),
    )

    return (
        decrement,
        euclidean,
        aliquot12,
        amicable,
        skolem2,
        syracuse,
        order6,
        floor54,
        matthews,
        switching,
        seven,
        order5,
        aliquot276,
        home,
        juggler,
        reverse_add,
        tag,
    )


def dump_board(path=None, memory=None, corpus=None) -> Path:
    from research_engine.diagnosis.corpus import ResearchCorpus
    from research_engine.memory.board import assemble_board
    from research_engine.memory.store import ResearchMemory

    store = memory if memory is not None else ResearchMemory.load_historical()
    session = corpus if corpus is not None else ResearchCorpus(
        tuple(item.diagnosis for item in store.experiments)
    )
    board = assemble_board(store, session)
    target = Path(path) if path is not None else BOARD_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    import json

    target.write_text(json.dumps(board.as_dict(), indent=2) + "\n", encoding="utf-8")
    return target


def load_board(path=None) -> TargetBoard:
    import json

    target = Path(path) if path is not None else BOARD_PATH
    return TargetBoard.from_dict(json.loads(target.read_text(encoding="utf-8")))
