"""Curated historical experiments. Not live attack output."""

from __future__ import annotations

from research_engine.diagnosis.types import (
    CapabilityCoverage,
    ExperimentRecord,
    FamilyStatus,
    RegimeFingerprint,
    ResearchDecision,
)
from research_engine.memory.types import (
    BlindPacket,
    DecisionReason,
    FailureClass,
    FailureRecord,
    FailureStatus,
    GreyLoot,
    GreyLootKind,
    ImportanceLevel,
    KnownEquivalent,
    LootEvidence,
    MathematicalYield,
    MemoryExperiment,
    NoveltyLevel,
    NoveltyStatus,
    PriorArtMemory,
    RunArtifact,
    ScoutDossier,
)

_FOLD_CORE = dict(
    state_space_type="INTEGER_1D",
    control_structure="SINGLETON",
    numerical_contraction="FINITE_CONTRACTING",
    eventual_region="FINITE_SEED_CLOSURE",
    orbit_behavior="FINITE_ORBIT",
    certificate_strength="EXACT_FINITE",
    transition_architecture="UNARY_MAP",
)


def _fp(**fields: str) -> RegimeFingerprint:
    return RegimeFingerprint(**fields)


def _cov(*names: str) -> CapabilityCoverage:
    statuses = {name: "EXERCISED" for name in names}
    return CapabilityCoverage(statuses=statuses)


def _diag(
    target: str,
    fingerprint: RegimeFingerprint,
    decision: ResearchDecision,
    reason: str,
    *,
    family_status: FamilyStatus = FamilyStatus.ACTIVE,
    family_id: str = "",
    prior: str = "",
    lean: str = "",
    exact: str = "",
    falsification: str = "",
    machinery: str = "",
) -> ExperimentRecord:
    if not family_id:
        key = fingerprint.core_key()
        family_id = "|".join(key) if key else "unclassified"
    semantic = family_id
    return ExperimentRecord(
        target=target,
        semantic_class=semantic,
        fingerprint=fingerprint,
        family_status=family_status,
        family_id=family_id,
        nearest_target="",
        structural_delta=None,
        coverage=_cov("finite_closure", "numerical_contraction"),
        strongest_exact=exact,
        strongest_falsification=falsification,
        lean_certificate=lean,
        prior_art_status=prior,
        reusable_machinery=machinery,
        decision=decision,
        decision_reason=reason,
    )


def _fail(
    exp_id: str,
    target: str,
    suffix: str,
    cls: FailureClass,
    representation: str,
    bottleneck: str,
    evidence: str,
    lesson: str,
    family: str,
    *,
    attack: str = "",
    phase: str = "diagnosis",
    value: ImportanceLevel = ImportanceLevel.MEDIUM,
    status: FailureStatus = FailureStatus.PARKED,
    action: str = "PARK",
    prior: str = "",
    counterexamples: tuple[str, ...] = (),
    example: str = "",
) -> FailureRecord:
    return FailureRecord(
        id=f"{exp_id}:{suffix}",
        target=target,
        experiment_id=exp_id,
        engine_version="0.2.1",
        phase=phase,
        attack=attack or family,
        failure_class=cls,
        representation_status=representation,
        mathematical_bottleneck=bottleneck,
        evidence=evidence,
        counterexamples=counterexamples,
        minimal_example=example,
        reusable_lesson=lesson,
        prior_art_status=prior,
        engineering_action=action,
        research_value=value,
        status=status,
        affected_attack_family=family,
    )


def historical_experiments() -> tuple[MemoryExperiment, ...]:
    fold_fp = _fp(**_FOLD_CORE)
    fold_id = "|".join(fold_fp.core_key() or ())
    fold_status = FamilyStatus.SATURATED

    signed = MemoryExperiment(
        experiment_id="signed_p0",
        target="operator_dynamics_benchmark",
        target_family="scalar_digit_fold",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "operator_dynamics_benchmark",
            fold_fp,
            ResearchDecision.CLOSE,
            "finite per-seed closure with local refutations and no new reusable abstraction",
            family_status=fold_status,
            family_id=fold_id,
            prior="KNOWN",
            exact="F^2 = P0 on the stated window",
        ),
        decision_reason_code=DecisionReason.FAMILY_SATURATED,
        representation_novelty=NoveltyLevel.NONE,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("operator family collapses to the known (P)-band",),
            unresolved_questions=("none; family saturated",),
        ),
        failures=(
            _fail(
                "signed_p0",
                "operator_dynamics_benchmark",
                "novelty",
                FailureClass.NOVELTY,
                "SCALAR_DIGIT_FOLD",
                "saturated_finite_contracting_regime",
                "finite orbit behavior; not a new dynamics class",
                "Further scalar digit-fold variants have low expected research value.",
                "scalar_fold",
                value=ImportanceLevel.LOW,
                prior="KNOWN",
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="signed_p0:loot:fold",
                kind=GreyLootKind.USEFUL_NEGATIVE_RESULT,
                statement="SignedP0 is a finite-contracting unary fold, not a new class",
                evidence=LootEvidence.SUPPORTED,
                experiment_id="signed_p0",
                target="operator_dynamics_benchmark",
                failure_class=FailureClass.NOVELTY,
                bottleneck="saturated_finite_contracting_regime",
            ),
        ),
        prior_art=PriorArtMemory(known_theorem_status="KNOWN", independently_rediscovered=True),
        blind_packet=BlindPacket(spec_name="operator_dynamics_benchmark", dimension=1),
        run_artifact=RunArtifact(census_kind="FINITE_CENSUS"),
        finalized=True,
    )

    digit = MemoryExperiment(
        experiment_id="digit_sum",
        target="balanced_ternary_digit_sum_dynamics",
        target_family="scalar_digit_fold",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "balanced_ternary_digit_sum_dynamics",
            fold_fp,
            ResearchDecision.CLOSE,
            "experiment reproduces a previously observed regime",
            family_status=fold_status,
            family_id=fold_id,
            prior="KNOWN",
        ),
        decision_reason_code=DecisionReason.FAMILY_SATURATED,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("scalar digit-fold family saturated",),
        ),
        failures=(
            _fail(
                "digit_sum",
                "balanced_ternary_digit_sum_dynamics",
                "novelty",
                FailureClass.NOVELTY,
                "SCALAR_DIGIT_FOLD",
                "saturated_finite_contracting_regime",
                "scalar digit-fold family saturated",
                "Further scalar digit-fold variants have low expected research value.",
                "scalar_fold",
                value=ImportanceLevel.LOW,
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="digit_sum:loot:sat",
                kind=GreyLootKind.USEFUL_NEGATIVE_RESULT,
                statement="digit-sum dynamics join the saturated fold family",
                evidence=LootEvidence.SUPPORTED,
                experiment_id="digit_sum",
                target="balanced_ternary_digit_sum_dynamics",
                failure_class=FailureClass.NOVELTY,
                bottleneck="saturated_finite_contracting_regime",
            ),
        ),
        blind_packet=BlindPacket(spec_name="balanced_ternary_digit_sum_dynamics", dimension=1),
        finalized=True,
    )

    weight = MemoryExperiment(
        experiment_id="weight_dynamics",
        target="balanced_ternary_weight_dynamics",
        target_family="scalar_digit_fold",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "balanced_ternary_weight_dynamics",
            fold_fp,
            ResearchDecision.FAMILY_SATURATED,
            "core fingerprint matches a saturated family",
            family_status=fold_status,
            family_id=fold_id,
            prior="KNOWN",
        ),
        decision_reason_code=DecisionReason.FAMILY_SATURATED,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(known_rediscoveries=("weight map saturates the digit-fold family",)),
        failures=(
            _fail(
                "weight_dynamics",
                "balanced_ternary_weight_dynamics",
                "novelty",
                FailureClass.NOVELTY,
                "SCALAR_DIGIT_FOLD",
                "saturated_finite_contracting_regime",
                "third independent fold; family SATURATED",
                "Further scalar digit-fold variants have low expected research value.",
                "scalar_fold",
                value=ImportanceLevel.LOW,
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="weight_dynamics:loot:sat",
                kind=GreyLootKind.USEFUL_NEGATIVE_RESULT,
                statement="weight dynamics saturates the digit-fold family",
                evidence=LootEvidence.SUPPORTED,
                experiment_id="weight_dynamics",
                target="balanced_ternary_weight_dynamics",
                failure_class=FailureClass.NOVELTY,
                bottleneck="saturated_finite_contracting_regime",
            ),
        ),
        blind_packet=BlindPacket(spec_name="balanced_ternary_weight_dynamics", dimension=1),
        finalized=True,
    )

    drift_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="EXPANDING",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="DRIFT",
        certificate_strength="OBSERVATION",
    )
    drift = MemoryExperiment(
        experiment_id="weight_drift",
        target="balanced_ternary_weight_drift",
        target_family="state_preserving_digit_perturbation",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "balanced_ternary_weight_drift",
            drift_fp,
            ResearchDecision.CLOSE,
            "expanding negative control; not a finite-contracting family member",
            family_id="INTEGER_1D|SINGLETON|EXPANDING|UNBOUNDED_SAMPLE|DRIFT|OBSERVATION",
            prior="KNOWN",
        ),
        decision_reason_code=DecisionReason.DISTINCT_REGIME,
        representation_novelty=NoveltyLevel.LOW,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.PROJECT_SPECIFIC,
        mathematical_yield=MathematicalYield(
            new_classifications=("state-preserving digit perturbation is a distinct regime",),
        ),
        grey_loot=(
            GreyLoot(
                id="weight_drift:loot:regime",
                kind=GreyLootKind.BRANCH_PATTERN,
                statement="WeightDrift is an expanding control and must not join the fold family",
                evidence=LootEvidence.SUPPORTED,
                experiment_id="weight_drift",
                target="balanced_ternary_weight_drift",
            ),
        ),
        blind_packet=BlindPacket(spec_name="balanced_ternary_weight_drift", dimension=1),
        finalized=True,
    )

    syr_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="EXACT_RELATION",
        piecewise_affine_structure="PARAMETERIZED",
        latent_control="PARAMETERIZED",
        parameter_domain="EXACT",
        latent_control_algebra="EXPLOITABLE",
        latent_control_obstruction="RECURSIVE_INVARIANT",
        affine_control_type="SCALAR",
    )
    syracuse = MemoryExperiment(
        experiment_id="syracuse",
        target="syracuse",
        target_family="latent_scalar_affine",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "syracuse",
            syr_fp,
            ResearchDecision.CONTINUE,
            "latent parameterized family recovered, domain certified, control-word algebra exploitable",
            prior="KNOWN",
            lean="Problems.Engine.Syracuse",
            exact="2^k y = 3x+1 on the certified domain",
            machinery="PiecewiseAffineCensus, ParameterDomain, ControlWord, control_obstruction",
        ),
        decision_reason_code=DecisionReason.KNOWN_REDISCOVERY,
        representation_novelty=NoveltyLevel.HIGH,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("accelerated odd-only 3x+1 / Syracuse map",),
            new_terminology=("latent residue control", "control-word algebra"),
            unresolved_questions=("map globality on Z remains empirical",),
            engineering_changes=0,
        ),
        failures=(
            _fail(
                "syracuse",
                "syracuse",
                "initial-representation",
                FailureClass.REPRESENTATION,
                "HIDDEN_2ADIC_CONTROL",
                "outside_affine_valuation_control",
                "initial run: hidden 2-adic control not represented",
                "Salvage was latent affine machinery; do not treat the initial gap as a standing PARK.",
                "latent_affine",
                attack="piecewise_affine",
                phase="census",
                status=FailureStatus.RESOLVED,
                action="SALVAGED",
                prior="KNOWN",
                value=ImportanceLevel.HIGH,
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="syracuse:loot:latent",
                kind=GreyLootKind.LATENT_CONTROL_PATTERN,
                statement="parameterized family 2^k y = 3x+1",
                evidence=LootEvidence.SUPPORTED,
                experiment_id="syracuse",
                target="syracuse",
            ),
            GreyLoot(
                id="syracuse:loot:obstruction",
                kind=GreyLootKind.OBSTRUCTION_PATTERN,
                statement="infinite class elimination possible without enumeration",
                evidence=LootEvidence.PROVED,
                experiment_id="syracuse",
                target="syracuse",
            ),
        ),
        prior_art=PriorArtMemory(
            literature_ids=("lagarias-2010-3x+1-survey",),
            semantic_equivalents=(
                KnownEquivalent(
                    known_equivalent=True,
                    engine_form="latent parameterized affine family with valuation control",
                    mathematical_meaning="equivalent",
                    literature_id="lagarias-2010-3x+1-survey",
                ),
            ),
            known_theorem_status="KNOWN",
            independently_rediscovered=True,
        ),
        scout=ScoutDossier(
            target="syracuse",
            problem_definition="accelerated odd-only Collatz / Syracuse map",
            literature=("lagarias-2010-3x+1-survey",),
        ),
        blind_packet=BlindPacket(spec_name="syracuse", dimension=1),
        run_artifact=RunArtifact(
            census_kind="PARAMETERIZED_CENSUS",
            lean_theorems=("Problems.Engine.Syracuse",),
        ),
        finalized=True,
    )

    control_obstruction = MemoryExperiment(
        experiment_id="control_obstruction",
        target="control_obstruction",
        target_family="latent_scalar_affine",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "control_obstruction",
            syr_fp,
            ResearchDecision.CONTINUE,
            "class-level obstruction without enumeration",
            prior="KNOWN",
            machinery="ControlObstructionCertificate",
        ),
        decision_reason_code=DecisionReason.SALVAGED_LANGUAGE,
        representation_novelty=NoveltyLevel.HIGH,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            new_obstructions=("infinite class elimination without enumeration",),
        ),
        grey_loot=(
            GreyLoot(
                id="control_obstruction:loot:class",
                kind=GreyLootKind.OBSTRUCTION_PATTERN,
                statement="class obstruction eliminates infinite families without listing words",
                evidence=LootEvidence.PROVED,
                experiment_id="control_obstruction",
                target="control_obstruction",
            ),
        ),
        blind_packet=BlindPacket(spec_name="control_obstruction", dimension=1),
        finalized=True,
    )

    remainder = MemoryExperiment(
        experiment_id="recursive_remainder",
        target="recursive_remainder",
        target_family="latent_scalar_affine",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "recursive_remainder",
            syr_fp,
            ResearchDecision.CONTINUE,
            "recursive remainder invariant; magnitude is not necessary",
            prior="KNOWN",
        ),
        decision_reason_code=DecisionReason.SALVAGED_LANGUAGE,
        representation_novelty=NoveltyLevel.HIGH,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            new_obstructions=("magnitude is not necessary for class obstruction",),
        ),
        grey_loot=(
            GreyLoot(
                id="recursive_remainder:loot:mag",
                kind=GreyLootKind.CANDIDATE_INVARIANT,
                statement="recursive remainder invariant obstructs classes without a magnitude Lyapunov",
                evidence=LootEvidence.PROVED,
                experiment_id="recursive_remainder",
                target="recursive_remainder",
            ),
        ),
        blind_packet=BlindPacket(spec_name="recursive_remainder", dimension=1),
        finalized=True,
    )

    euc_fp = _fp(
        state_space_type="INTEGER_VECTOR",
        control_structure="SINGLETON",
        numerical_contraction="FINITE_CONTRACTING",
        eventual_region="FINITE_SEED_CLOSURE",
        orbit_behavior="FINITE_ORBIT",
        certificate_strength="EXACT_FINITE",
        affine_control_type="VECTOR",
        piecewise_affine_structure="PARAMETERIZED",
        latent_control="PARAMETERIZED",
    )
    euclidean = MemoryExperiment(
        experiment_id="euclidean_quotient",
        target="euclidean_quotient",
        target_family="vector_affine",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "euclidean_quotient",
            euc_fp,
            ResearchDecision.CLOSE,
            "vector remainder dynamics; scalar affine census inapplicable",
            prior="KNOWN",
            machinery="vector_affine",
        ),
        decision_reason_code=DecisionReason.SALVAGED_LANGUAGE,
        representation_novelty=NoveltyLevel.HIGH,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("Euclidean remainder dynamics",),
            new_terminology=("vector affine representation",),
        ),
        failures=(
            _fail(
                "euclidean_quotient",
                "euclidean_quotient",
                "scalar",
                FailureClass.REPRESENTATION,
                "SCALAR_AFFINE_INSUFFICIENT",
                "outside_affine_valuation_control",
                "scalar affine census cannot represent vector controlled dynamics",
                "Salvage was vector_affine; do not add a Euclidean-specific attack.",
                "latent_affine",
                attack="piecewise_affine",
                status=FailureStatus.RESOLVED,
                action="SALVAGED",
                value=ImportanceLevel.HIGH,
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="euclidean_quotient:loot:vector",
                kind=GreyLootKind.LATENT_CONTROL_PATTERN,
                statement="vector affine family recovers remainder dynamics",
                evidence=LootEvidence.SUPPORTED,
                experiment_id="euclidean_quotient",
                target="euclidean_quotient",
            ),
        ),
        blind_packet=BlindPacket(spec_name="euclidean_quotient", dimension=2),
        run_artifact=RunArtifact(skipped=("piecewise_affine",), attack_statuses={"vector_affine": "SUPPORTED"}),
        finalized=True,
    )

    mat_fp = _fp(
        state_space_type="INTEGER_VECTOR",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="EXACT_RELATION",
        affine_control_type="MATRIX_PARAMETERIZED",
        latent_control_obstruction="RECURSIVE_INVARIANT",
        piecewise_affine_structure="PARAMETERIZED",
    )
    matrix_word = MemoryExperiment(
        experiment_id="matrix_word_invariant",
        target="matrix_word_invariant",
        target_family="matrix_affine",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "matrix_word_invariant",
            mat_fp,
            ResearchDecision.CONTINUE,
            "vector class obstruction can use lattice/gcd structure",
            prior="KNOWN",
            machinery="matrix_word_invariant",
        ),
        decision_reason_code=DecisionReason.SALVAGED_LANGUAGE,
        representation_novelty=NoveltyLevel.HIGH,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            new_obstructions=("matrix-word recursive invariant / lattice gcd",),
            new_terminology=("matrix-word representation",),
        ),
        grey_loot=(
            GreyLoot(
                id="matrix_word_invariant:loot:gcd",
                kind=GreyLootKind.OBSTRUCTION_PATTERN,
                statement="vector class obstruction uses lattice/gcd structure",
                evidence=LootEvidence.PROVED,
                experiment_id="matrix_word_invariant",
                target="matrix_word_invariant",
            ),
        ),
        blind_packet=BlindPacket(spec_name="matrix_word_invariant", dimension=2),
        finalized=True,
    )

    slc_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="BRANCHING",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="NONDETERMINISTIC",
        certificate_strength="OBSERVATION",
        piecewise_affine_structure="UNCERTAIN",
    )
    sum_strip = MemoryExperiment(
        experiment_id="sum_strip_slc",
        target="sum_strip",
        target_family="nondeterministic_slc",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "sum_strip",
            slc_fp,
            ResearchDecision.ENGINE_LIMITATION,
            "overlapping branches diagnosed; deterministic control cannot consume them",
            prior="KNOWN",
        ),
        decision_reason_code=DecisionReason.QUANTIFIER_MISMATCH,
        representation_novelty=NoveltyLevel.LOW,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("nondeterministic one-variable linear-constraint loop",),
            unresolved_questions=("quantifier-aware consumption of overlapping branches",),
            engineering_changes=0,
        ),
        failures=(
            _fail(
                "sum_strip_slc",
                "sum_strip",
                "quantifier",
                FailureClass.QUANTIFIER,
                "NONDETERMINISTIC_BRANCHING",
                "overlapping_existential_branches",
                "branching diagnosed but deterministic control language cannot consume overlapping branches",
                "PARK; do not implement a nondeterministic control attack from this instance.",
                "deterministic_control",
                attack="control_word",
                value=ImportanceLevel.MEDIUM,
                prior="KNOWN",
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="sum_strip_slc:loot:branch",
                kind=GreyLootKind.QUANTIFIER_MISMATCH,
                statement="overlapping existential branches",
                evidence=LootEvidence.OBSERVED,
                experiment_id="sum_strip_slc",
                target="sum_strip",
                failure_class=FailureClass.QUANTIFIER,
                bottleneck="overlapping_existential_branches",
            ),
        ),
        scout=ScoutDossier(target="sum_strip", problem_definition="sum-strip SLC", literature=("carelli-2026-loop-termination",)),
        blind_packet=BlindPacket(spec_name="sum_strip", dimension=1),
        finalized=True,
    )

    two_affine = MemoryExperiment(
        experiment_id="two_affine_slc",
        target="two_affine",
        target_family="nondeterministic_slc",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "two_affine",
            slc_fp,
            ResearchDecision.ENGINE_LIMITATION,
            "overlapping affine branches; deterministic control skipped",
            prior="KNOWN",
        ),
        decision_reason_code=DecisionReason.QUANTIFIER_MISMATCH,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(engineering_changes=0),
        failures=(
            _fail(
                "two_affine_slc",
                "two_affine",
                "quantifier",
                FailureClass.QUANTIFIER,
                "NONDETERMINISTIC_BRANCHING",
                "overlapping_existential_branches",
                "two overlapping affine branches",
                "PARK; do not implement.",
                "deterministic_control",
                attack="control_word",
                value=ImportanceLevel.MEDIUM,
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="two_affine_slc:loot:branch",
                kind=GreyLootKind.QUANTIFIER_MISMATCH,
                statement="two overlapping affine branches",
                evidence=LootEvidence.OBSERVED,
                experiment_id="two_affine_slc",
                target="two_affine",
                failure_class=FailureClass.QUANTIFIER,
                bottleneck="overlapping_existential_branches",
            ),
        ),
        blind_packet=BlindPacket(spec_name="two_affine", dimension=1),
        finalized=True,
    )

    involution_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="EXPANDING",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="PERIOD_2",
        certificate_strength="OBSERVATION",
        piecewise_affine_structure="UNCERTAIN",
    )
    involution = MemoryExperiment(
        experiment_id="involution_census",
        target="negation",
        target_family="involution",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "negation",
            involution_fp,
            ResearchDecision.ENGINE_LIMITATION,
            "sign-first region inference truncates y = -x",
            prior="KNOWN",
        ),
        decision_reason_code=DecisionReason.RECURRING_ENGINE_LIMITATION,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            unresolved_questions=("complete census of the involution x |-> -x",),
            engineering_changes=0,
        ),
        failures=(
            _fail(
                "involution_census",
                "negation",
                "domain",
                FailureClass.DOMAIN_INFERENCE,
                "SIGN_TRUNCATED_AFFINE",
                "sign_first_region_inference",
                "sign-first region inference truncates a globally valid affine law",
                "Do not implement the census fix during v2.2.",
                "piecewise_affine",
                attack="piecewise_affine",
                action="DO_NOT_IMPLEMENT",
                value=ImportanceLevel.MEDIUM,
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="involution_census:loot:sign",
                kind=GreyLootKind.FAILED_DOMAIN_PREDICATE,
                statement="sign-first partition misses y = -x",
                evidence=LootEvidence.REFUTED,
                experiment_id="involution_census",
                target="negation",
                failure_class=FailureClass.DOMAIN_INFERENCE,
                bottleneck="sign_first_region_inference",
            ),
        ),
        blind_packet=BlindPacket(spec_name="negation", dimension=1),
        run_artifact=RunArtifact(census_kind="UNRESOLVED"),
        finalized=True,
    )

    rplus_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="EXACT_RELATION",
        piecewise_affine_structure="PARAMETERIZED",
        latent_control="PARAMETERIZED",
        parameter_domain="EXACT",
        latent_control_algebra="EXPLOITABLE",
        affine_control_type="SCALAR",
    )
    rplus = MemoryExperiment(
        experiment_id="carelli_rplus",
        target="rplus",
        target_family="generalized_collatz",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "rplus",
            rplus_fp,
            ResearchDecision.CONTINUE,
            "frozen v2 reconstructs generalized-Collatz language; global reachability unresolved",
            prior="KNOWN",
            lean="Problems.Engine.LinearConstraintLoops",
            exact="3y=4x-1 and 3y=4x-2 on residues 1 and 2 mod 3",
        ),
        decision_reason_code=DecisionReason.KNOWN_REDISCOVERY,
        representation_novelty=NoveltyLevel.HIGH,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("Carelli R+ integer graph / Matthews–Watts",),
            unresolved_questions=("global reachability on R+",),
            engineering_changes=0,
        ),
        failures=(
            _fail(
                "carelli_rplus",
                "rplus",
                "global",
                FailureClass.GLOBAL_REASONING,
                "LANGUAGE_ADEQUATE",
                "finite_to_infinite_certificate",
                "state language reconstructed; infinite-time reachability unresolved",
                "Representation fit is not an infinite-time theorem.",
                "global_reachability",
                attack="closure",
                value=ImportanceLevel.HIGH,
                prior="KNOWN",
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="carelli_rplus:loot:family",
                kind=GreyLootKind.LATENT_CONTROL_PATTERN,
                statement="3y=4x-1 / 3y=4x-2",
                evidence=LootEvidence.SUPPORTED,
                experiment_id="carelli_rplus",
                target="rplus",
            ),
        ),
        prior_art=PriorArtMemory(
            literature_ids=("carelli-2026-loop-termination", "matthews-watts-1984-generalization-hasse"),
            semantic_equivalents=(
                KnownEquivalent(
                    known_equivalent=True,
                    engine_form="residue-controlled affine family on R+",
                    mathematical_meaning="equivalent",
                    literature_id="carelli-2026-loop-termination",
                ),
            ),
            independently_rediscovered=True,
            known_theorem_status="KNOWN",
        ),
        scout=ScoutDossier(target="rplus", literature=("carelli-2026-loop-termination",)),
        blind_packet=BlindPacket(spec_name="rplus", dimension=1),
        run_artifact=RunArtifact(
            census_kind="PARAMETERIZED_CENSUS",
            lean_theorems=("Problems.Engine.LinearConstraintLoops",),
        ),
        finalized=True,
    )

    bb5_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="EXACT_RELATION",
        piecewise_affine_structure="PARAMETERIZED",
        affine_control_type="SCALAR",
        parameter_domain="EXACT",
    )
    bb5 = MemoryExperiment(
        experiment_id="bb5_map",
        target="bb5_map",
        target_family="generalized_collatz",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "bb5_map",
            bb5_fp,
            ResearchDecision.FAMILY_SATURATED,
            "frozen v2 reconstructs known residue-controlled affine language",
            family_status=FamilyStatus.SATURATED,
            prior="KNOWN",
            exact="3y=5x+18 / 3y=5x+22",
        ),
        decision_reason_code=DecisionReason.KNOWN_REDISCOVERY,
        representation_novelty=NoveltyLevel.HIGH,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("BB-5 residue-controlled affine map",),
            unresolved_questions=("remaining convergence problem is known",),
        ),
        failures=(
            _fail(
                "bb5_map",
                "bb5_map",
                "global",
                FailureClass.GLOBAL_REASONING,
                "LANGUAGE_ADEQUATE",
                "finite_to_infinite_certificate",
                "residue-controlled language recovered; convergence remains the known open problem",
                "Do not treat known convergence as a new engine theorem.",
                "global_reachability",
                attack="closure",
                value=ImportanceLevel.HIGH,
                prior="KNOWN",
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="bb5_map:loot:family",
                kind=GreyLootKind.LATENT_CONTROL_PATTERN,
                statement="3y=5x+18 on 0 mod 3; 3y=5x+22 on 1 mod 3",
                evidence=LootEvidence.SUPPORTED,
                experiment_id="bb5_map",
                target="bb5_map",
            ),
        ),
        prior_art=PriorArtMemory(
            independently_rediscovered=True,
            known_theorem_status="KNOWN",
            semantic_equivalents=(
                KnownEquivalent(
                    known_equivalent=True,
                    engine_form="residue-controlled affine family",
                    mathematical_meaning="equivalent",
                ),
            ),
        ),
        scout=ScoutDossier(target="bb5_map"),
        blind_packet=BlindPacket(spec_name="bb5_map", dimension=1),
        run_artifact=RunArtifact(census_kind="PARAMETERIZED_CENSUS"),
        finalized=True,
    )

    aliquot_fp = _fp(
        state_space_type="INTEGER_1D",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="OBSERVATION",
        piecewise_affine_structure="UNCERTAIN",
    )
    aliquot = MemoryExperiment(
        experiment_id="aliquot_276",
        target="aliquot_276",
        target_family="divisor_sum",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08",
        diagnosis=_diag(
            "aliquot_276",
            aliquot_fp,
            ResearchDecision.ENGINE_LIMITATION,
            "singleton control, mixed magnitude, truncated reachable set, no affine language",
            prior="KNOWN",
            lean="Problems.Engine.AliquotDynamics",
            falsification="descent refuted at seed 12",
        ),
        decision_reason_code=DecisionReason.REPRESENTATION_MISMATCH,
        representation_novelty=NoveltyLevel.NONE,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("aliquot prefix of 276 matches A008892",),
            new_counterexamples=("descent refuted at 12",),
            unresolved_questions=("fate of seed 276",),
            engineering_changes=0,
        ),
        failures=(
            _fail(
                "aliquot_276",
                "aliquot_276",
                "representation",
                FailureClass.REPRESENTATION,
                "NON_AFFINE",
                "outside_affine_valuation_control",
                "n |-> sigma(n)-n does not naturally fit affine/valuation control",
                "PARK; do not implement an aliquot attack.",
                "latent_affine",
                attack="piecewise_affine",
                value=ImportanceLevel.HIGH,
                prior="KNOWN",
                example="n |-> sigma(n)-n",
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="aliquot_276:loot:mismatch",
                kind=GreyLootKind.REPRESENTATION_MISMATCH,
                statement="sigma(n)-n is outside affine/control language",
                evidence=LootEvidence.OBSERVED,
                experiment_id="aliquot_276",
                target="aliquot_276",
                failure_class=FailureClass.REPRESENTATION,
                bottleneck="outside_affine_valuation_control",
            ),
        ),
        scout=ScoutDossier(target="aliquot_276", literature=("oeis-A008892",)),
        blind_packet=BlindPacket(spec_name="aliquot_276", dimension=1, max_states=32),
        run_artifact=RunArtifact(census_kind="UNRESOLVED", lean_theorems=("Problems.Engine.AliquotDynamics",)),
        finalized=True,
    )

    skolem_fp = _fp(
        state_space_type="INTEGER_VECTOR",
        control_structure="SINGLETON",
        numerical_contraction="MIXED_MAGNITUDE",
        eventual_region="UNBOUNDED_SAMPLE",
        orbit_behavior="MIXED",
        certificate_strength="FINITE_RANGE",
        affine_control_type="VECTOR",
    )
    skolem = MemoryExperiment(
        experiment_id="skolem_order6",
        target="companion_shift_order6",
        target_family="linear_recurrence",
        adapter_version="0.2.1",
        engine_version="0.2.1",
        experiment_date="2026-08-25",
        diagnosis=_diag(
            "companion_shift_order6",
            skolem_fp,
            ResearchDecision.CLOSE,
            "representation fits vector-affine language; infinite zero reachability unresolved",
            prior="KNOWN",
            lean="Problems.Engine.CompanionShift",
            exact="companion_shift_order6_eleventh_negative",
            falsification="fixed sign refuted at n=11",
        ),
        decision_reason_code=DecisionReason.GLOBAL_REACHABILITY_GAP,
        representation_novelty=NoveltyLevel.LOW,
        mathematical_novelty=NoveltyLevel.NONE,
        novelty_status=NoveltyStatus.KNOWN_REDISCOVERY,
        mathematical_yield=MathematicalYield(
            known_rediscoveries=("order-6 companion window of Bacik et al. 2026 survey (13)",),
            new_counterexamples=("u_11 < 0",),
            new_formalizations=("Problems.Engine.CompanionShift",),
            unresolved_questions=("whether survey sequence (13) vanishes",),
            engineering_changes=0,
        ),
        failures=(
            _fail(
                "skolem_order6",
                "companion_shift_order6",
                "global",
                FailureClass.GLOBAL_REASONING,
                "LANGUAGE_ADEQUATE",
                "finite_to_infinite_certificate",
                "finite computation does not decide infinite zero reachability",
                "Representation fit is not a Skolem decision procedure.",
                "global_reachability",
                attack="closure",
                value=ImportanceLevel.HIGH,
                prior="KNOWN",
                counterexamples=("u_11 < 0",),
            ),
            _fail(
                "skolem_order6",
                "companion_shift_order6",
                "computational",
                FailureClass.COMPUTATIONAL,
                "VECTOR_AFFINE_ADEQUATE",
                "finite_budget_exhausted",
                "25^6 census cube skipped; COMPUTATION_EXHAUSTED",
                "Computational blockage is not mathematical impossibility.",
                "vector_census",
                attack="vector_affine",
                value=ImportanceLevel.MEDIUM,
                prior="KNOWN",
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="skolem_order6:loot:budget",
                kind=GreyLootKind.COMPUTATIONAL_BOTTLENECK,
                statement="vector census 25^6 exceeds 50000 cells",
                evidence=LootEvidence.FINITE_RANGE,
                experiment_id="skolem_order6",
                target="companion_shift_order6",
                failure_class=FailureClass.COMPUTATIONAL,
                bottleneck="finite_budget_exhausted",
            ),
            GreyLoot(
                id="skolem_order6:loot:sign",
                kind=GreyLootKind.COUNTEREXAMPLE,
                statement="fixed-sign conjecture refuted at n=11",
                evidence=LootEvidence.REFUTED,
                experiment_id="skolem_order6",
                target="companion_shift_order6",
                payload={"witness": "11"},
            ),
        ),
        prior_art=PriorArtMemory(
            literature_ids=(
                "bacik-et-al-2026-skolem-positivity-survey",
                "lipton-et-al-2022-skolem-conjecture",
            ),
            independently_rediscovered=False,
            known_theorem_status="OPEN",
        ),
        scout=ScoutDossier(
            target="companion_shift_order6",
            problem_definition="Does the order-6 integer LRS of the 2026 survey vanish?",
            literature=("bacik-et-al-2026-skolem-positivity-survey",),
        ),
        blind_packet=BlindPacket(
            spec_name="companion_shift_order6",
            dimension=6,
            skip_attacks=("vector_affine",),
            max_states=32,
            max_steps=16,
        ),
        run_artifact=RunArtifact(
            attack_statuses={"vector_affine": "COMPUTATION_EXHAUSTED"},
            lean_theorems=("Problems.Engine.CompanionShift",),
        ),
        finalized=True,
    )

    hygiene = MemoryExperiment(
        experiment_id="skolem_lrs_hygiene",
        target="skolem_lrs",
        target_family="experiment_hygiene",
        adapter_version="0.2.1",
        engine_version="0.2.2",
        experiment_date="2026-08-25",
        diagnosis=_diag(
            "skolem_lrs",
            skolem_fp,
            ResearchDecision.CLOSE,
            "token-leak false positive on the problem identifier",
            prior="KNOWN",
        ),
        decision_reason_code=DecisionReason.EXPERIMENT_HYGIENE,
        novelty_status=NoveltyStatus.PROJECT_SPECIFIC,
        mathematical_yield=MathematicalYield(engineering_changes=0),
        failures=(
            _fail(
                "skolem_lrs_hygiene",
                "skolem_lrs",
                "hygiene",
                FailureClass.EXPERIMENT_HYGIENE,
                "N_A",
                "identifier_token_false_positive",
                "problem id skolem_lrs matched a forbidden literature token",
                "Allowlist package ids; match literature tokens only in adapter/spec/planner sources.",
                "hygiene",
                attack="literature_leak",
                phase="benchmark",
                status=FailureStatus.RESOLVED,
                action="RESOLVED",
                value=ImportanceLevel.LOW,
            ),
        ),
        grey_loot=(
            GreyLoot(
                id="skolem_lrs_hygiene:loot:token",
                kind=GreyLootKind.USEFUL_NEGATIVE_RESULT,
                statement="skolem_lrs as an identifier is not a literature leak",
                evidence=LootEvidence.REFUTED,
                experiment_id="skolem_lrs_hygiene",
                target="skolem_lrs",
                failure_class=FailureClass.EXPERIMENT_HYGIENE,
                bottleneck="identifier_token_false_positive",
            ),
        ),
        blind_packet=BlindPacket(spec_name="companion_shift_order6", dimension=6),
        finalized=True,
    )

    return (
        signed,
        digit,
        weight,
        drift,
        syracuse,
        control_obstruction,
        remainder,
        euclidean,
        matrix_word,
        sum_strip,
        two_affine,
        involution,
        rplus,
        bb5,
        aliquot,
        skolem,
        hygiene,
    )


def dump_historical(path=None):
    from pathlib import Path

    from research_engine.memory.store import SEED_PATH, ResearchMemory

    target = Path(path) if path is not None else SEED_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    ResearchMemory(historical_experiments()).to_json(target)
    return target
