from research.open_problems.definition import ProblemDefinition

PROBLEM = ProblemDefinition(
    id="operator_dynamics",
    title="Compositions and orbits of balanced-ternary operators",
    status="ARCHIVED",
    statement=(
        "Every exact identity of word length at most 4 in the monoid "
        "generated by {S,N,D,W} is a consequence of the recorded operator "
        "identities. Generic operator definitions remain in bt.operators."
    ),
    bt_relevance="All maps act on canonical balanced-ternary words or integers.",
    docs=(
        "docs/problems/operator_dynamics.md",
        "docs/operator_algebra.md",
    ),
)
