"""Render docs/theory/theorem_ledger.md from theorem_ledger.json.

The markdown table is generated. Edit the JSON, then run this script.
Pass --check to fail if the markdown is stale (CI).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "docs" / "theory" / "theorem_ledger.json"
MD_PATH = ROOT / "docs" / "theory" / "theorem_ledger.md"

HEADER = """# Theorem ledger

Machine-readable sibling: [theorem_ledger.json](theorem_ledger.json).

This file is generated by `tools/render_theorem_ledger.py`. Edit the JSON.

Tags:

- `EXACT — LEAN VERIFIED`
- `EXACT — HUMAN PROOF`
- `COMPUTATIONALLY VERIFIED`
- `CONJECTURE`
- `OBSERVATION`
- `REFUTED`
- `REPARAMETERIZATION`

Provenance is copied from the mathematical record and Lean sources.
This ledger does not rewrite history.

| ID | Tag | Statement (short) | Source | Lean | Tests |
|----|-----|-------------------|--------|------|-------|
"""


def _short_lean(path: str) -> str:
    if not path:
        return ""
    return path.removeprefix("formal/").removesuffix(".lean")


def _short_tests(paths: list[str]) -> str:
    names = []
    for p in paths:
        names.append(Path(p).stem)
    return ", ".join(names)


def render(entries: list[dict]) -> str:
    lines = [HEADER]
    for row in entries:
        tests = _short_tests(list(row.get("tests") or []))
        lean = _short_lean(str(row.get("lean") or ""))
        statement = str(row.get("statement") or "").replace("|", "\\|")
        source = str(row.get("source") or "")
        lines.append(
            f"| {row['id']} | {row['tag']} | {statement} | {source} | {lean} | {tests} |\n"
        )
    return "".join(lines)


def load_entries() -> list[dict]:
    return json.loads(JSON_PATH.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if theorem_ledger.md does not match the JSON",
    )
    args = parser.parse_args(argv)
    text = render(load_entries())
    if args.check:
        current = MD_PATH.read_text(encoding="utf-8") if MD_PATH.exists() else ""
        if current != text:
            print("docs/theory/theorem_ledger.md is stale; run tools/render_theorem_ledger.py")
            return 1
        return 0
    MD_PATH.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
