"""Descriptor for balanced-ternary prime residual complexity."""

from research.open_problems.definition import ProblemDefinition

PROBLEM = ProblemDefinition(
    id="prime_residual_complexity",
    title="Prime residual complexity in balanced ternary",
    status="ARCHIVED",
    statement=(
        "How does the exact residual state space generated by LSD-first "
        "balanced-ternary sections grow when the observable is primality, "
        "compared with the finite residual of a fixed modular sieve? "
        "This module does not claim a primality test or a new non-automaticity theorem."
    ),
    bt_relevance=(
        "States are residual arguments of existing I_a; windows are integer_jet. "
        "The sieve control is the DFA n ↦ 3n+a on Z/MZ with trit alphabet {-1,0,1}."
    ),
    docs=("docs/problems/prime_residual_complexity.md",),
    lean=("formal/Problems/Primes/Residual.lean",),
)
